//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TripDBEntities1 : DbContext
    {
        public TripDBEntities1()
            : base("name=TripDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buss> Buss { get; set; }
        public virtual DbSet<Trip> Trip { get; set; }
        public virtual DbSet<TripPlan> TripPlan { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
